# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- releases/*
stages:
- stage: Dev
  variables:
  - group: devenvvariables
  jobs:
  - job: Dev
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo "Developement environment build"
    - script: echo "Using subscription $(subid)"
    - script: echo "The environment variable is $(envname)"
    - task: CreateBlueprint@1
      inputs:
        azureSubscription: 'BinghamDev (6edd3889-d778-4efa-a9d8-2653d60d531f)'
        BlueprintName: 'baseblueprint.json'
        BlueprintPath: '.'
        AlternateLocation: false
        PublishBlueprint: false
    - task: AssignBlueprint@1
      inputs:
        azureSubscription: 'BinghamDev (6edd3889-d778-4efa-a9d8-2653d60d531f)'
        AssignmentName: 'AssignDevBlueprint'
        BlueprintName: 'baseblueprint.json'
        ParametersFile: '.'
        AlternateSubscription: false
- stage: Test
  variables:
  - group: testenvvariables
  jobs:
  - job: Test
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo "Test environment build"
    - script: echo "Using subscription $(subid)"
    - script: echo "The environment variable is $(envname)"
- stage: Stage
  variables:
  - group: stageenvvariables
  jobs:
  - job: Stage
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo "Stage environment build"
    - script: echo "Using subscription $(subid)"
    - script: echo "The environment variable is $(envname)"
- stage: Prod
  variables:
  - group: prodenvvariables
  jobs:
  - job: Prod
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo "Prod environment build"
    - script: echo "Using subscription $(subid)"
    - script: echo "The environment variable is $(envname)"


