# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Dev
  jobs:
  - jobs: Dev
    pool:
      vmImage: 'vs2017-win2016'
    continueOnError: false
    steps:
    - script: echo "Developement environment build"
- stage: Test
  jobs:
  - jobs: Test
    pool:
      vmImage: 'vs2017-win2016'
    continueOnError: false
    steps:
    - script: echo "Test environment build"
- stage: Stage
  jobs:
  - jobs: Stage
    pool:
      vmImage: 'vs2017-win2016'
    continueOnError: false
    steps:
    - script: echo "Stage environment build"
- stage: Prod
  jobs:
  - jobs: Prod
    pool:
      vmImage: 'vs2017-win2016'
    continueOnError: false
    steps:
    - script: echo "Prod environment build"


